### ISSUE TITLE
mbdiscid and MBID

### ISSUE THREAD

**Issue by pzs7602** [Zastai/MetaBrainz.MusicBrainz.dotnet-mbdiscid#18]
I use this project to get my disc mbdiscid:
dotnet mbdiscid

which gives the mbdiscid value: vzbAWGqLaZcRwHSJpNCxF.X7QNc-
what's the relation between mbdiscid and musicbrainz's MBID(36 characters) ?

**Comment by Zastai** [comment]
There is no direct relation between the values. The disc id represents the physical layout of a CD (number of tracks, lengths, etc). It's not unique.

An MBID is a unique identifier assigned to a MusicBrainz entity (artist, instrument, release, work, ...).

Releases can have one or more disc IDs assigned to them. And a disc ID can be associated with multiple releases. One of the things mbdiscid will output is a submission url; opening that should bring up a MusicBrainz page that will show you what release(s) the disc id is linked to (if any) and allow you to look for another release to link it with.

**Comment by pzs7602** [comment]
Thank you  for the reply.
Can I get MBID by using one of your MetaBrainz project? Could you please give an example for how to use MusicBrainz.CoverArt to get an audio disc coverart?

**Comment by Zastai** [comment]
The main MusicBrainz project has an API for looking up the releases (if any) associated with a disc id.

And for the cover art, you will need a release MBID.

So to have one application that goes from disc in drive to its cover art, you'd need three libraries (musicbrainz, musicbrainz.discid and musicbrainz.coverart).

Or you could just use MusicBrainz Picard to do that for you.

**Comment by pzs7602** [comment]
Thanks, I'll have a try

**Comment by pzs7602** [comment]
I try to use the mbdiscid returned from MetaBrainz.MusicBrainz.dotnet-mbdiscid to get the barcode of the disc and then get the release MBID:
```
            Query query = new Query();
            // discd is mbdiscid got from MetaBrainz.MusicBrainz.dotnet-mbdiscid
            var cd_result = query.FindCdStubs("discid:vzbAWGqLaZcRwHSJpNCxF.X7QNc-");
            if (cd_result.Results.Count > 0)
            {
              // handle the first matching item
              string barcode = cd_result.Results[0].Item.Barcode;
              var rel_result = query.FindReleases("barcode:"+barcode);
              foreach (var result in rel_result.Results)
              {
                   // handle MBID in result.Item.Id

              }
            }
```
But I found query.FindCdStubs("discid:vzbAWGqLaZcRwHSJpNCxF.X7QNc-") always returns 0 results(I've used some different discs). What's wrong with my code?

**Comment by Zastai** [comment]
CD Stubs are a very particular thing; they're information about a CD (usually imported from freedb.org) for which no release has been created yet. You almost never need/want to use those.

The API you want is `LookupDiscId` (in general, the `FindXxx` APIs are for "I don't know exactly what I want but I know something about it", whereas the `LookupXxx` APIs are for "I know the thing's main identifier").
It returns a results structure with 3 alternatives:
- an `IDisc`; this means the ID is linked to one or more releases.
  You can then walk the list of linked releases to see which one matches yours. In the case of your disc, there is only one linked
  release (a Von Karajan performance of Shostakovich's 10th symphony).
  Those releases in the list will already include information about whether they have associated cover art archive contents.
  If that indicates there is cover art, you can use their ID to retrieve it.
- a `ICdStub`; this means there is no linked or similar release in musicbrainz, so you can't get at cover art with any degree of certainty
- a list of `IReleases`; this is the fallback fuzzy lookup; it will contain releases where the lengths of the tracks seem to match the disc ID
  - you can then still do cover art lookup based on those releases, but you'll need to take care because there is no strong link to the disc ID

```csharp
// assumes an instance of Query called query and an instance of CoverArt called caa
var result = query.LookupDiscId("vzbAWGqLaZcRwHSJpNCxF.X7QNc-");
if (result.Disc?.Releases is not null) {
  foreach (var release in result.Disc.Releases) {
    var art = release.CoverArtArchive;
    if (art is not null and art.Artwork) {
      // there is artwork available
      if (art.Front) {
        var image = caa.FetchFront(release.Id)?.Decode;
        // work with the image
      }
      if (art.Back) {
        var image = caa.FetchBack(release.Id)?.Decode;
        // work with the image
      }
    }
    else {
      // if there's no artwork on the release, you could check its release group, but that's less likely to match your disc
    }
  }
}
else if (result.Releases is not null) {
  // similar processing as for result.Disc.Releases, keeping in mind these releases are less certain to be related to the disc ID
}
```

**Comment by pzs7602** [comment]
WOW! The reply is really helpful, Thank you very much!
